name: device_track
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2

  google_maps_flutter: ^2.2.4 #---------
  url_launcher: ^6.0.20 #-----
  flutter_inappwebview: 5.4.4
  geolocator: ^9.0.2 # get user pos (gps)
  http: any

  shared_preferences: ^2.0.15 #ios Storage location : NSUserDefaults

  fluttertoast: ^8.0.8
  geocoding: ^2.0.2 # convert address to latlng

  intl_phone_number_input: ^0.7.0+2
  awesome_dialog: ^3.0.2

  line_icons: ^2.0.3

  google_fonts: ^4.0.4

  path_provider: any
  open_file: any

  #uuid: 3.0.6
  animated_text_kit: any
  intl: any
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  collection: ^1.15.0
  expansion_tile_card: ^3.0.0
  pinch_zoom: ^1.0.0
  font_awesome_flutter: ^10.4.0 #icons
  #ionicons: ^0.2.2 #icons
  email_validator: '^2.1.16'
  custom_map_markers: ^0.0.1
  dropdown_button2: ^1.6.3 # used for item options dropdown
  #flutter_easyloading: any
  introduction_screen: any
  #date_format: any
  settings_ui: ^2.0.2
  flutter_typeahead: ^4.0.0 # for textField in appbar
  responsive_sizer: ^3.1.0
  cached_network_image: any #  with downloading image

  fancy_shimmer_image: ^2.0.2
  alarm: any

  auto_size_text: ^3.0.0
  timezone: any
  flutter_datetime_picker_plus: ^2.2.0

  numberpicker: ^2.1.2
  flutter_animated_dialog: any
  flutter_advanced_drawer: ^1.3.5
  pdf: ^3.10.4
  printing: any
  connectivity_plus: ^4.0.1
  fl_chart: ^0.63.0
  flutter_launcher_icons: ^0.13.1
  loader_overlay: any
  loading_animation_widget: any
  flutter_spinkit: any
  flutter_easyloading: ^3.0.5
  loading_indicator: ^3.1.0
  easy_date_timeline: ^1.0.5
  flutter_swipe_action_cell: ^3.1.3
  persistent_bottom_nav_bar: ^5.0.2
  flutter_staggered_animations: ^1.1.1
  custom_refresh_indicator: ^3.0.0
  flutter_hooks: ^0.20.5
  animations: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
